/* automatically generated by rust-bindgen */

extern "C" {
    pub fn Example(s: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn Get(id: ::std::os::raw::c_int) -> *mut ::std::os::raw::c_char;
}
